// <copyright file="MainForm.Designer.cs" company="PublicDomainWeekly.com">
//     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
//     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// </copyright>
// <auto-generated />

namespace HotkeyRun
{
    partial class MainForm
    {
        /// <summary>
        /// Designer variable used to keep track of non-visual components.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Disposes resources used by the form.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// This method is required for Windows Forms designer support.
        /// Do not change the method contents inside the source code editor. The Forms designer might
        /// not be able to load this method if it was changed manually.
        /// </summary>
        private void InitializeComponent()
        {
        	System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
        	this.openFileDialog = new System.Windows.Forms.OpenFileDialog();
        	this.alwaysOnTopToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.optionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.minimizeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.mainMenuStrip = new System.Windows.Forms.MenuStrip();
        	this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.newToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.openToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.toolStripSeparator = new System.Windows.Forms.ToolStripSeparator();
        	this.saveToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.saveAsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
        	this.printToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.printPreviewToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.toolStripSeparator3 = new System.Windows.Forms.ToolStripSeparator();
        	this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.weeklyReleasesPublicDomainWeeklycomToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.originalThreadDonationCodercomToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.sourceCodeGithubcomToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
        	this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.saveFileDialog = new System.Windows.Forms.SaveFileDialog();
        	this.replayedCountToolStripStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
        	this.mainToolStripStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
        	this.mainStatusStrip = new System.Windows.Forms.StatusStrip();
        	this.collectedToolStripStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
        	this.collectedCountToolStripStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
        	this.mainTableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
        	this.hotkeyCombinationLabel = new System.Windows.Forms.Label();
        	this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
        	this.controlCheckBox = new System.Windows.Forms.CheckBox();
        	this.altCheckBox = new System.Windows.Forms.CheckBox();
        	this.shiftCheckBox = new System.Windows.Forms.CheckBox();
        	this.keyComboBox = new System.Windows.Forms.ComboBox();
        	this.addButton = new System.Windows.Forms.Button();
        	this.removeButton = new System.Windows.Forms.Button();
        	this.activeRadioButton = new System.Windows.Forms.RadioButton();
        	this.inactiveRadioButton = new System.Windows.Forms.RadioButton();
        	this.commandArgumentLabel = new System.Windows.Forms.Label();
        	this.programListBox = new System.Windows.Forms.ListBox();
        	this.argumentTextBox = new System.Windows.Forms.TextBox();
        	this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
        	this.browseButton = new System.Windows.Forms.Button();
        	this.commandTextBox = new System.Windows.Forms.TextBox();
        	this.mainMenuStrip.SuspendLayout();
        	this.mainStatusStrip.SuspendLayout();
        	this.mainTableLayoutPanel.SuspendLayout();
        	this.tableLayoutPanel1.SuspendLayout();
        	this.tableLayoutPanel2.SuspendLayout();
        	this.SuspendLayout();
        	// 
        	// openFileDialog
        	// 
        	this.openFileDialog.DefaultExt = "txt";
        	this.openFileDialog.Filter = "TXT Files|*.txt|All files (*.*)|*.*";
        	// 
        	// alwaysOnTopToolStripMenuItem
        	// 
        	this.alwaysOnTopToolStripMenuItem.Name = "alwaysOnTopToolStripMenuItem";
        	this.alwaysOnTopToolStripMenuItem.Size = new System.Drawing.Size(149, 22);
        	this.alwaysOnTopToolStripMenuItem.Text = "&Always on top";
        	// 
        	// optionsToolStripMenuItem
        	// 
        	this.optionsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.alwaysOnTopToolStripMenuItem});
        	this.optionsToolStripMenuItem.Name = "optionsToolStripMenuItem";
        	this.optionsToolStripMenuItem.Size = new System.Drawing.Size(61, 20);
        	this.optionsToolStripMenuItem.Text = "&Options";
        	this.optionsToolStripMenuItem.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.OnOptionsToolStripMenuItemDropDownItemClicked);
        	// 
        	// minimizeToolStripMenuItem
        	// 
        	this.minimizeToolStripMenuItem.Alignment = System.Windows.Forms.ToolStripItemAlignment.Right;
        	this.minimizeToolStripMenuItem.Name = "minimizeToolStripMenuItem";
        	this.minimizeToolStripMenuItem.Size = new System.Drawing.Size(12, 20);
        	this.minimizeToolStripMenuItem.Visible = false;
        	// 
        	// mainMenuStrip
        	// 
        	this.mainMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.minimizeToolStripMenuItem,
        	        	        	this.fileToolStripMenuItem,
        	        	        	this.optionsToolStripMenuItem,
        	        	        	this.helpToolStripMenuItem});
        	this.mainMenuStrip.Location = new System.Drawing.Point(0, 0);
        	this.mainMenuStrip.Name = "mainMenuStrip";
        	this.mainMenuStrip.Size = new System.Drawing.Size(288, 24);
        	this.mainMenuStrip.TabIndex = 33;
        	// 
        	// fileToolStripMenuItem
        	// 
        	this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.newToolStripMenuItem,
        	        	        	this.openToolStripMenuItem,
        	        	        	this.toolStripSeparator,
        	        	        	this.saveToolStripMenuItem,
        	        	        	this.saveAsToolStripMenuItem,
        	        	        	this.toolStripSeparator1,
        	        	        	this.printToolStripMenuItem,
        	        	        	this.printPreviewToolStripMenuItem,
        	        	        	this.toolStripSeparator3,
        	        	        	this.exitToolStripMenuItem});
        	this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
        	this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
        	this.fileToolStripMenuItem.Text = "&File";
        	// 
        	// newToolStripMenuItem
        	// 
        	this.newToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("newToolStripMenuItem.Image")));
        	this.newToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
        	this.newToolStripMenuItem.Name = "newToolStripMenuItem";
        	this.newToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.N)));
        	this.newToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
        	this.newToolStripMenuItem.Text = "&New";
        	this.newToolStripMenuItem.Click += new System.EventHandler(this.OnNewToolStripMenuItemClick);
        	// 
        	// openToolStripMenuItem
        	// 
        	this.openToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("openToolStripMenuItem.Image")));
        	this.openToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
        	this.openToolStripMenuItem.Name = "openToolStripMenuItem";
        	this.openToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.O)));
        	this.openToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
        	this.openToolStripMenuItem.Text = "&Open";
        	this.openToolStripMenuItem.Click += new System.EventHandler(this.OnOpenToolStripMenuItemClick);
        	// 
        	// toolStripSeparator
        	// 
        	this.toolStripSeparator.Name = "toolStripSeparator";
        	this.toolStripSeparator.Size = new System.Drawing.Size(143, 6);
        	// 
        	// saveToolStripMenuItem
        	// 
        	this.saveToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("saveToolStripMenuItem.Image")));
        	this.saveToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
        	this.saveToolStripMenuItem.Name = "saveToolStripMenuItem";
        	this.saveToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.S)));
        	this.saveToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
        	this.saveToolStripMenuItem.Text = "&Save";
        	this.saveToolStripMenuItem.Click += new System.EventHandler(this.OnSaveToolStripMenuItemClick);
        	// 
        	// saveAsToolStripMenuItem
        	// 
        	this.saveAsToolStripMenuItem.Name = "saveAsToolStripMenuItem";
        	this.saveAsToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
        	this.saveAsToolStripMenuItem.Text = "Save &As";
        	this.saveAsToolStripMenuItem.Visible = false;
        	// 
        	// toolStripSeparator1
        	// 
        	this.toolStripSeparator1.Name = "toolStripSeparator1";
        	this.toolStripSeparator1.Size = new System.Drawing.Size(143, 6);
        	this.toolStripSeparator1.Visible = false;
        	// 
        	// printToolStripMenuItem
        	// 
        	this.printToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("printToolStripMenuItem.Image")));
        	this.printToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
        	this.printToolStripMenuItem.Name = "printToolStripMenuItem";
        	this.printToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.P)));
        	this.printToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
        	this.printToolStripMenuItem.Text = "&Print";
        	this.printToolStripMenuItem.Visible = false;
        	// 
        	// printPreviewToolStripMenuItem
        	// 
        	this.printPreviewToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("printPreviewToolStripMenuItem.Image")));
        	this.printPreviewToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
        	this.printPreviewToolStripMenuItem.Name = "printPreviewToolStripMenuItem";
        	this.printPreviewToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
        	this.printPreviewToolStripMenuItem.Text = "Print Pre&view";
        	this.printPreviewToolStripMenuItem.Visible = false;
        	// 
        	// toolStripSeparator3
        	// 
        	this.toolStripSeparator3.Name = "toolStripSeparator3";
        	this.toolStripSeparator3.Size = new System.Drawing.Size(143, 6);
        	// 
        	// exitToolStripMenuItem
        	// 
        	this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
        	this.exitToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
        	this.exitToolStripMenuItem.Text = "E&xit";
        	this.exitToolStripMenuItem.Click += new System.EventHandler(this.OnExitToolStripMenuItemClick);
        	// 
        	// helpToolStripMenuItem
        	// 
        	this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.weeklyReleasesPublicDomainWeeklycomToolStripMenuItem,
        	        	        	this.originalThreadDonationCodercomToolStripMenuItem,
        	        	        	this.sourceCodeGithubcomToolStripMenuItem,
        	        	        	this.toolStripSeparator2,
        	        	        	this.aboutToolStripMenuItem});
        	this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
        	this.helpToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
        	this.helpToolStripMenuItem.Text = "&Help";
        	// 
        	// weeklyReleasesPublicDomainWeeklycomToolStripMenuItem
        	// 
        	this.weeklyReleasesPublicDomainWeeklycomToolStripMenuItem.Name = "weeklyReleasesPublicDomainWeeklycomToolStripMenuItem";
        	this.weeklyReleasesPublicDomainWeeklycomToolStripMenuItem.Size = new System.Drawing.Size(313, 22);
        	this.weeklyReleasesPublicDomainWeeklycomToolStripMenuItem.Text = "&Weekly releases @ PublicDomainWeekly.com";
        	this.weeklyReleasesPublicDomainWeeklycomToolStripMenuItem.Click += new System.EventHandler(this.OnWeeklyReleasesPublicDomainWeeklycomToolStripMenuItemClick);
        	// 
        	// originalThreadDonationCodercomToolStripMenuItem
        	// 
        	this.originalThreadDonationCodercomToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("originalThreadDonationCodercomToolStripMenuItem.Image")));
        	this.originalThreadDonationCodercomToolStripMenuItem.Name = "originalThreadDonationCodercomToolStripMenuItem";
        	this.originalThreadDonationCodercomToolStripMenuItem.Size = new System.Drawing.Size(313, 22);
        	this.originalThreadDonationCodercomToolStripMenuItem.Text = "&Original thread @ DonationCoder.com";
        	this.originalThreadDonationCodercomToolStripMenuItem.Click += new System.EventHandler(this.OnOriginalThreadDonationCodercomToolStripMenuItemClick);
        	// 
        	// sourceCodeGithubcomToolStripMenuItem
        	// 
        	this.sourceCodeGithubcomToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("sourceCodeGithubcomToolStripMenuItem.Image")));
        	this.sourceCodeGithubcomToolStripMenuItem.Name = "sourceCodeGithubcomToolStripMenuItem";
        	this.sourceCodeGithubcomToolStripMenuItem.Size = new System.Drawing.Size(313, 22);
        	this.sourceCodeGithubcomToolStripMenuItem.Text = "Source code @ Github.com";
        	this.sourceCodeGithubcomToolStripMenuItem.Click += new System.EventHandler(this.OnSourceCodeGithubcomToolStripMenuItemClick);
        	// 
        	// toolStripSeparator2
        	// 
        	this.toolStripSeparator2.Name = "toolStripSeparator2";
        	this.toolStripSeparator2.Size = new System.Drawing.Size(310, 6);
        	// 
        	// aboutToolStripMenuItem
        	// 
        	this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
        	this.aboutToolStripMenuItem.Size = new System.Drawing.Size(313, 22);
        	this.aboutToolStripMenuItem.Text = "&About...";
        	this.aboutToolStripMenuItem.Click += new System.EventHandler(this.OnAboutToolStripMenuItemClick);
        	// 
        	// saveFileDialog
        	// 
        	this.saveFileDialog.DefaultExt = "txt";
        	this.saveFileDialog.Filter = "TXT Files|*.txt|All files (*.*)|*.*";
        	// 
        	// replayedCountToolStripStatusLabel
        	// 
        	this.replayedCountToolStripStatusLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.replayedCountToolStripStatusLabel.Name = "replayedCountToolStripStatusLabel";
        	this.replayedCountToolStripStatusLabel.Size = new System.Drawing.Size(14, 17);
        	this.replayedCountToolStripStatusLabel.Text = "0";
        	// 
        	// mainToolStripStatusLabel
        	// 
        	this.mainToolStripStatusLabel.Name = "mainToolStripStatusLabel";
        	this.mainToolStripStatusLabel.Size = new System.Drawing.Size(36, 17);
        	this.mainToolStripStatusLabel.Text = "Runs:";
        	// 
        	// mainStatusStrip
        	// 
        	this.mainStatusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.collectedToolStripStatusLabel,
        	        	        	this.collectedCountToolStripStatusLabel,
        	        	        	this.mainToolStripStatusLabel,
        	        	        	this.replayedCountToolStripStatusLabel});
        	this.mainStatusStrip.Location = new System.Drawing.Point(0, 314);
        	this.mainStatusStrip.Name = "mainStatusStrip";
        	this.mainStatusStrip.Size = new System.Drawing.Size(288, 22);
        	this.mainStatusStrip.SizingGrip = false;
        	this.mainStatusStrip.TabIndex = 32;
        	// 
        	// collectedToolStripStatusLabel
        	// 
        	this.collectedToolStripStatusLabel.Name = "collectedToolStripStatusLabel";
        	this.collectedToolStripStatusLabel.Size = new System.Drawing.Size(43, 17);
        	this.collectedToolStripStatusLabel.Text = "Count:";
        	// 
        	// collectedCountToolStripStatusLabel
        	// 
        	this.collectedCountToolStripStatusLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
        	this.collectedCountToolStripStatusLabel.Name = "collectedCountToolStripStatusLabel";
        	this.collectedCountToolStripStatusLabel.Size = new System.Drawing.Size(14, 17);
        	this.collectedCountToolStripStatusLabel.Text = "0";
        	// 
        	// mainTableLayoutPanel
        	// 
        	this.mainTableLayoutPanel.ColumnCount = 2;
        	this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
        	this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
        	this.mainTableLayoutPanel.Controls.Add(this.hotkeyCombinationLabel, 0, 0);
        	this.mainTableLayoutPanel.Controls.Add(this.tableLayoutPanel1, 0, 1);
        	this.mainTableLayoutPanel.Controls.Add(this.addButton, 0, 5);
        	this.mainTableLayoutPanel.Controls.Add(this.removeButton, 1, 5);
        	this.mainTableLayoutPanel.Controls.Add(this.activeRadioButton, 0, 7);
        	this.mainTableLayoutPanel.Controls.Add(this.inactiveRadioButton, 1, 7);
        	this.mainTableLayoutPanel.Controls.Add(this.commandArgumentLabel, 0, 2);
        	this.mainTableLayoutPanel.Controls.Add(this.programListBox, 0, 6);
        	this.mainTableLayoutPanel.Controls.Add(this.argumentTextBox, 0, 4);
        	this.mainTableLayoutPanel.Controls.Add(this.tableLayoutPanel2, 0, 3);
        	this.mainTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.mainTableLayoutPanel.Location = new System.Drawing.Point(0, 24);
        	this.mainTableLayoutPanel.Name = "mainTableLayoutPanel";
        	this.mainTableLayoutPanel.RowCount = 8;
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
        	this.mainTableLayoutPanel.Size = new System.Drawing.Size(288, 290);
        	this.mainTableLayoutPanel.TabIndex = 34;
        	// 
        	// hotkeyCombinationLabel
        	// 
        	this.mainTableLayoutPanel.SetColumnSpan(this.hotkeyCombinationLabel, 2);
        	this.hotkeyCombinationLabel.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.hotkeyCombinationLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.hotkeyCombinationLabel.Location = new System.Drawing.Point(3, 0);
        	this.hotkeyCombinationLabel.Name = "hotkeyCombinationLabel";
        	this.hotkeyCombinationLabel.Size = new System.Drawing.Size(282, 20);
        	this.hotkeyCombinationLabel.TabIndex = 0;
        	this.hotkeyCombinationLabel.Text = "&Hotkey combination:";
        	this.hotkeyCombinationLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
        	// 
        	// tableLayoutPanel1
        	// 
        	this.tableLayoutPanel1.ColumnCount = 4;
        	this.mainTableLayoutPanel.SetColumnSpan(this.tableLayoutPanel1, 2);
        	this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
        	this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
        	this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
        	this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
        	this.tableLayoutPanel1.Controls.Add(this.controlCheckBox, 0, 0);
        	this.tableLayoutPanel1.Controls.Add(this.altCheckBox, 1, 0);
        	this.tableLayoutPanel1.Controls.Add(this.shiftCheckBox, 2, 0);
        	this.tableLayoutPanel1.Controls.Add(this.keyComboBox, 3, 0);
        	this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 20);
        	this.tableLayoutPanel1.Margin = new System.Windows.Forms.Padding(0);
        	this.tableLayoutPanel1.Name = "tableLayoutPanel1";
        	this.tableLayoutPanel1.RowCount = 1;
        	this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
        	this.tableLayoutPanel1.Size = new System.Drawing.Size(288, 25);
        	this.tableLayoutPanel1.TabIndex = 3;
        	// 
        	// controlCheckBox
        	// 
        	this.controlCheckBox.Location = new System.Drawing.Point(3, 3);
        	this.controlCheckBox.Name = "controlCheckBox";
        	this.controlCheckBox.Size = new System.Drawing.Size(66, 19);
        	this.controlCheckBox.TabIndex = 1;
        	this.controlCheckBox.Text = "&CTRL";
        	this.controlCheckBox.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
        	this.controlCheckBox.UseVisualStyleBackColor = true;
        	// 
        	// altCheckBox
        	// 
        	this.altCheckBox.Location = new System.Drawing.Point(75, 3);
        	this.altCheckBox.Name = "altCheckBox";
        	this.altCheckBox.Size = new System.Drawing.Size(66, 19);
        	this.altCheckBox.TabIndex = 2;
        	this.altCheckBox.Text = "&ALT";
        	this.altCheckBox.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
        	this.altCheckBox.UseVisualStyleBackColor = true;
        	// 
        	// shiftCheckBox
        	// 
        	this.shiftCheckBox.Location = new System.Drawing.Point(147, 3);
        	this.shiftCheckBox.Name = "shiftCheckBox";
        	this.shiftCheckBox.Size = new System.Drawing.Size(66, 19);
        	this.shiftCheckBox.TabIndex = 3;
        	this.shiftCheckBox.Text = "&SHIFT";
        	this.shiftCheckBox.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
        	this.shiftCheckBox.UseVisualStyleBackColor = true;
        	// 
        	// keyComboBox
        	// 
        	this.keyComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        	this.keyComboBox.FormattingEnabled = true;
        	this.keyComboBox.Location = new System.Drawing.Point(219, 3);
        	this.keyComboBox.Name = "keyComboBox";
        	this.keyComboBox.Size = new System.Drawing.Size(66, 21);
        	this.keyComboBox.TabIndex = 4;
        	// 
        	// addButton
        	// 
        	this.addButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.addButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.addButton.Location = new System.Drawing.Point(10, 116);
        	this.addButton.Margin = new System.Windows.Forms.Padding(10, 1, 10, 1);
        	this.addButton.Name = "addButton";
        	this.addButton.Size = new System.Drawing.Size(124, 28);
        	this.addButton.TabIndex = 9;
        	this.addButton.Text = "&Add";
        	this.addButton.UseVisualStyleBackColor = true;
        	this.addButton.Click += new System.EventHandler(this.OnAddButtonClick);
        	// 
        	// removeButton
        	// 
        	this.removeButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.removeButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.removeButton.Location = new System.Drawing.Point(154, 116);
        	this.removeButton.Margin = new System.Windows.Forms.Padding(10, 1, 10, 1);
        	this.removeButton.Name = "removeButton";
        	this.removeButton.Size = new System.Drawing.Size(124, 28);
        	this.removeButton.TabIndex = 10;
        	this.removeButton.Text = "&Remove";
        	this.removeButton.UseVisualStyleBackColor = true;
        	this.removeButton.Click += new System.EventHandler(this.OnRemoveButtonClick);
        	// 
        	// activeRadioButton
        	// 
        	this.activeRadioButton.CheckAlign = System.Drawing.ContentAlignment.MiddleRight;
        	this.activeRadioButton.Checked = true;
        	this.activeRadioButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.activeRadioButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.activeRadioButton.Location = new System.Drawing.Point(3, 268);
        	this.activeRadioButton.Name = "activeRadioButton";
        	this.activeRadioButton.Size = new System.Drawing.Size(138, 19);
        	this.activeRadioButton.TabIndex = 12;
        	this.activeRadioButton.TabStop = true;
        	this.activeRadioButton.Text = "&Active";
        	this.activeRadioButton.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
        	this.activeRadioButton.UseVisualStyleBackColor = true;
        	this.activeRadioButton.Click += new System.EventHandler(this.OnRadioButtonClick);
        	// 
        	// inactiveRadioButton
        	// 
        	this.inactiveRadioButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.inactiveRadioButton.Location = new System.Drawing.Point(147, 268);
        	this.inactiveRadioButton.Name = "inactiveRadioButton";
        	this.inactiveRadioButton.Size = new System.Drawing.Size(138, 19);
        	this.inactiveRadioButton.TabIndex = 13;
        	this.inactiveRadioButton.Text = "&Inactive";
        	this.inactiveRadioButton.UseVisualStyleBackColor = true;
        	this.inactiveRadioButton.Click += new System.EventHandler(this.OnRadioButtonClick);
        	// 
        	// commandArgumentLabel
        	// 
        	this.mainTableLayoutPanel.SetColumnSpan(this.commandArgumentLabel, 2);
        	this.commandArgumentLabel.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.commandArgumentLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.commandArgumentLabel.Location = new System.Drawing.Point(3, 45);
        	this.commandArgumentLabel.Name = "commandArgumentLabel";
        	this.commandArgumentLabel.Size = new System.Drawing.Size(282, 20);
        	this.commandArgumentLabel.TabIndex = 5;
        	this.commandArgumentLabel.Text = "&Command + arguments";
        	this.commandArgumentLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
        	// 
        	// programListBox
        	// 
        	this.mainTableLayoutPanel.SetColumnSpan(this.programListBox, 2);
        	this.programListBox.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.programListBox.FormattingEnabled = true;
        	this.programListBox.Location = new System.Drawing.Point(3, 148);
        	this.programListBox.Name = "programListBox";
        	this.programListBox.Size = new System.Drawing.Size(282, 114);
        	this.programListBox.TabIndex = 11;
        	// 
        	// argumentTextBox
        	// 
        	this.mainTableLayoutPanel.SetColumnSpan(this.argumentTextBox, 2);
        	this.argumentTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.argumentTextBox.Location = new System.Drawing.Point(3, 93);
        	this.argumentTextBox.Name = "argumentTextBox";
        	this.argumentTextBox.Size = new System.Drawing.Size(282, 20);
        	this.argumentTextBox.TabIndex = 8;
        	// 
        	// tableLayoutPanel2
        	// 
        	this.tableLayoutPanel2.ColumnCount = 2;
        	this.mainTableLayoutPanel.SetColumnSpan(this.tableLayoutPanel2, 2);
        	this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 75F));
        	this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
        	this.tableLayoutPanel2.Controls.Add(this.browseButton, 1, 0);
        	this.tableLayoutPanel2.Controls.Add(this.commandTextBox, 0, 0);
        	this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.tableLayoutPanel2.Location = new System.Drawing.Point(0, 65);
        	this.tableLayoutPanel2.Margin = new System.Windows.Forms.Padding(0);
        	this.tableLayoutPanel2.Name = "tableLayoutPanel2";
        	this.tableLayoutPanel2.RowCount = 1;
        	this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
        	this.tableLayoutPanel2.Size = new System.Drawing.Size(288, 25);
        	this.tableLayoutPanel2.TabIndex = 11;
        	// 
        	// browseButton
        	// 
        	this.browseButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.browseButton.Location = new System.Drawing.Point(219, 1);
        	this.browseButton.Margin = new System.Windows.Forms.Padding(3, 1, 3, 1);
        	this.browseButton.Name = "browseButton";
        	this.browseButton.Size = new System.Drawing.Size(66, 23);
        	this.browseButton.TabIndex = 7;
        	this.browseButton.Text = "&Browse";
        	this.browseButton.UseVisualStyleBackColor = true;
        	this.browseButton.Click += new System.EventHandler(this.OnBrowseButtonClick);
        	// 
        	// commandTextBox
        	// 
        	this.commandTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.commandTextBox.Location = new System.Drawing.Point(3, 3);
        	this.commandTextBox.Name = "commandTextBox";
        	this.commandTextBox.Size = new System.Drawing.Size(210, 20);
        	this.commandTextBox.TabIndex = 6;
        	// 
        	// MainForm
        	// 
        	this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
        	this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        	this.ClientSize = new System.Drawing.Size(288, 336);
        	this.Controls.Add(this.mainTableLayoutPanel);
        	this.Controls.Add(this.mainMenuStrip);
        	this.Controls.Add(this.mainStatusStrip);
        	this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
        	this.Name = "MainForm";
        	this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
        	this.Text = "HotkeyRun";
        	this.mainMenuStrip.ResumeLayout(false);
        	this.mainMenuStrip.PerformLayout();
        	this.mainStatusStrip.ResumeLayout(false);
        	this.mainStatusStrip.PerformLayout();
        	this.mainTableLayoutPanel.ResumeLayout(false);
        	this.mainTableLayoutPanel.PerformLayout();
        	this.tableLayoutPanel1.ResumeLayout(false);
        	this.tableLayoutPanel2.ResumeLayout(false);
        	this.tableLayoutPanel2.PerformLayout();
        	this.ResumeLayout(false);
        	this.PerformLayout();
        }
        private System.Windows.Forms.TextBox commandTextBox;
        private System.Windows.Forms.Button browseButton;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.TextBox argumentTextBox;
        private System.Windows.Forms.ListBox programListBox;
        private System.Windows.Forms.Label commandArgumentLabel;
        private System.Windows.Forms.RadioButton inactiveRadioButton;
        private System.Windows.Forms.RadioButton activeRadioButton;
        private System.Windows.Forms.Button removeButton;
        private System.Windows.Forms.Button addButton;
        private System.Windows.Forms.CheckBox shiftCheckBox;
        private System.Windows.Forms.CheckBox altCheckBox;
        private System.Windows.Forms.CheckBox controlCheckBox;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.ComboBox keyComboBox;
        private System.Windows.Forms.Label hotkeyCombinationLabel;
        private System.Windows.Forms.TableLayoutPanel mainTableLayoutPanel;
        private System.Windows.Forms.ToolStripStatusLabel collectedCountToolStripStatusLabel;
        private System.Windows.Forms.ToolStripStatusLabel collectedToolStripStatusLabel;
        private System.Windows.Forms.StatusStrip mainStatusStrip;
        private System.Windows.Forms.ToolStripStatusLabel mainToolStripStatusLabel;
        private System.Windows.Forms.ToolStripStatusLabel replayedCountToolStripStatusLabel;
        private System.Windows.Forms.SaveFileDialog saveFileDialog;
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.ToolStripMenuItem sourceCodeGithubcomToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem originalThreadDonationCodercomToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem weeklyReleasesPublicDomainWeeklycomToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator3;
        private System.Windows.Forms.ToolStripMenuItem printPreviewToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem printToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripMenuItem saveAsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem saveToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator;
        private System.Windows.Forms.ToolStripMenuItem openToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem newToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.MenuStrip mainMenuStrip;
        private System.Windows.Forms.ToolStripMenuItem minimizeToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem optionsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem alwaysOnTopToolStripMenuItem;
        private System.Windows.Forms.OpenFileDialog openFileDialog;
    }
}
